# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed Jun 10 18:01:20 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

import sys
from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(658, 365)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(120, 10, 41, 16))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(220, 10, 41, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(340, 10, 41, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(460, 10, 41, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(580, 10, 41, 16))
        self.label_5.setObjectName("label_5")
        self.curTemp1 = QtGui.QLCDNumber(self.centralWidget)
        self.curTemp1.setGeometry(QtCore.QRect(110, 40, 51, 21))
        self.curTemp1.setObjectName("curTemp1")
        self.targetTemp1 = QtGui.QLCDNumber(self.centralWidget)
        self.targetTemp1.setGeometry(QtCore.QRect(110, 80, 51, 21))
        self.targetTemp1.setObjectName("targetTemp1")
        self.fanLevel1 = QtGui.QLCDNumber(self.centralWidget)
        self.fanLevel1.setGeometry(QtCore.QRect(110, 120, 51, 21))
        self.fanLevel1.setObjectName("fanLevel1")
        self.label_6 = QtGui.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(20, 40, 59, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(20, 80, 59, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(20, 120, 59, 16))
        self.label_8.setObjectName("label_8")
        self.cost1 = QtGui.QLCDNumber(self.centralWidget)
        self.cost1.setGeometry(QtCore.QRect(110, 160, 51, 21))
        self.cost1.setObjectName("cost1")
        self.label_9 = QtGui.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(20, 160, 59, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(20, 260, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.fanLevel2 = QtGui.QLCDNumber(self.centralWidget)
        self.fanLevel2.setGeometry(QtCore.QRect(210, 120, 51, 21))
        self.fanLevel2.setObjectName("fanLevel2")
        self.targetTemp2 = QtGui.QLCDNumber(self.centralWidget)
        self.targetTemp2.setGeometry(QtCore.QRect(210, 80, 51, 21))
        self.targetTemp2.setObjectName("targetTemp2")
        self.cost2 = QtGui.QLCDNumber(self.centralWidget)
        self.cost2.setGeometry(QtCore.QRect(210, 160, 51, 21))
        self.cost2.setObjectName("cost2")
        self.curTemp2 = QtGui.QLCDNumber(self.centralWidget)
        self.curTemp2.setGeometry(QtCore.QRect(210, 40, 51, 21))
        self.curTemp2.setObjectName("curTemp2")
        self.fanLevel3 = QtGui.QLCDNumber(self.centralWidget)
        self.fanLevel3.setGeometry(QtCore.QRect(330, 120, 51, 21))
        self.fanLevel3.setObjectName("fanLevel3")
        self.targetTemp3 = QtGui.QLCDNumber(self.centralWidget)
        self.targetTemp3.setGeometry(QtCore.QRect(330, 80, 51, 21))
        self.targetTemp3.setObjectName("targetTemp3")
        self.cost3 = QtGui.QLCDNumber(self.centralWidget)
        self.cost3.setGeometry(QtCore.QRect(330, 160, 51, 21))
        self.cost3.setObjectName("cost3")
        self.curTemp3 = QtGui.QLCDNumber(self.centralWidget)
        self.curTemp3.setGeometry(QtCore.QRect(330, 40, 51, 21))
        self.curTemp3.setObjectName("curTemp3")
        self.fanLevel4 = QtGui.QLCDNumber(self.centralWidget)
        self.fanLevel4.setGeometry(QtCore.QRect(450, 120, 51, 21))
        self.fanLevel4.setObjectName("fanLevel4")
        self.targetTemp4 = QtGui.QLCDNumber(self.centralWidget)
        self.targetTemp4.setGeometry(QtCore.QRect(450, 80, 51, 21))
        self.targetTemp4.setObjectName("targetTemp4")
        self.cost4 = QtGui.QLCDNumber(self.centralWidget)
        self.cost4.setGeometry(QtCore.QRect(450, 160, 51, 21))
        self.cost4.setObjectName("cost4")
        self.curTemp4 = QtGui.QLCDNumber(self.centralWidget)
        self.curTemp4.setGeometry(QtCore.QRect(450, 40, 51, 21))
        self.curTemp4.setObjectName("curTemp4")
        self.fanLevel5 = QtGui.QLCDNumber(self.centralWidget)
        self.fanLevel5.setGeometry(QtCore.QRect(570, 120, 51, 21))
        self.fanLevel5.setObjectName("fanLevel5")
        self.targetTemp5 = QtGui.QLCDNumber(self.centralWidget)
        self.targetTemp5.setGeometry(QtCore.QRect(570, 80, 51, 21))
        self.targetTemp5.setObjectName("targetTemp5")
        self.cost5 = QtGui.QLCDNumber(self.centralWidget)
        self.cost5.setGeometry(QtCore.QRect(570, 160, 51, 21))
        self.cost5.setObjectName("cost5")
        self.curTemp5 = QtGui.QLCDNumber(self.centralWidget)
        self.curTemp5.setGeometry(QtCore.QRect(570, 40, 51, 21))
        self.curTemp5.setObjectName("curTemp5")
        self.modeLabel = QtGui.QLabel(self.centralWidget)
        self.modeLabel.setGeometry(QtCore.QRect(80, 260, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.modeLabel.setFont(font)
        self.modeLabel.setText("")
        self.modeLabel.setObjectName("modeLabel")
        self.checkout2 = QtGui.QPushButton(self.centralWidget)
        self.checkout2.setGeometry(QtCore.QRect(100, 220, 71, 31))
        self.checkout2.setObjectName("checkout2")
        self.checkin1 = QtGui.QPushButton(self.centralWidget)
        self.checkin1.setGeometry(QtCore.QRect(100, 190, 71, 31))
        self.checkin1.setObjectName("checkin1")
        self.checkin2 = QtGui.QPushButton(self.centralWidget)
        self.checkin2.setGeometry(QtCore.QRect(200, 190, 71, 31))
        self.checkin2.setObjectName("checkin2")
        self.checkout2_2 = QtGui.QPushButton(self.centralWidget)
        self.checkout2_2.setGeometry(QtCore.QRect(200, 220, 71, 31))
        self.checkout2_2.setObjectName("checkout2_2")
        self.checkin3 = QtGui.QPushButton(self.centralWidget)
        self.checkin3.setGeometry(QtCore.QRect(320, 190, 71, 31))
        self.checkin3.setObjectName("checkin3")
        self.checkout3 = QtGui.QPushButton(self.centralWidget)
        self.checkout3.setGeometry(QtCore.QRect(320, 220, 71, 31))
        self.checkout3.setObjectName("checkout3")
        self.checkin4 = QtGui.QPushButton(self.centralWidget)
        self.checkin4.setGeometry(QtCore.QRect(440, 190, 71, 31))
        self.checkin4.setObjectName("checkin4")
        self.checkout4 = QtGui.QPushButton(self.centralWidget)
        self.checkout4.setGeometry(QtCore.QRect(440, 220, 71, 31))
        self.checkout4.setObjectName("checkout4")
        self.checkin5 = QtGui.QPushButton(self.centralWidget)
        self.checkin5.setGeometry(QtCore.QRect(560, 190, 71, 31))
        self.checkin5.setObjectName("checkin5")
        self.checkout5 = QtGui.QPushButton(self.centralWidget)
        self.checkout5.setGeometry(QtCore.QRect(560, 220, 71, 31))
        self.checkout5.setObjectName("checkout5")
        self.dayReport = QtGui.QPushButton(self.centralWidget)
        self.dayReport.setGeometry(QtCore.QRect(310, 260, 91, 32))
        self.dayReport.setObjectName("dayReport")
        self.weekReport = QtGui.QPushButton(self.centralWidget)
        self.weekReport.setGeometry(QtCore.QRect(420, 260, 91, 32))
        self.weekReport.setObjectName("weekReport")
        self.monthReport = QtGui.QPushButton(self.centralWidget)
        self.monthReport.setGeometry(QtCore.QRect(530, 260, 91, 32))
        self.monthReport.setObjectName("monthReport")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar()
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 658, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "房间1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "房间2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "房间3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "房间4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "房间5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "当前温度", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "目标温度", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "当前风速", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "金额", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "模式", None, QtGui.QApplication.UnicodeUTF8))
        self.checkout2.setText(QtGui.QApplication.translate("MainWindow", "退房", None, QtGui.QApplication.UnicodeUTF8))
        self.checkin1.setText(QtGui.QApplication.translate("MainWindow", "入住", None, QtGui.QApplication.UnicodeUTF8))
        self.checkin2.setText(QtGui.QApplication.translate("MainWindow", "入住", None, QtGui.QApplication.UnicodeUTF8))
        self.checkout2_2.setText(QtGui.QApplication.translate("MainWindow", "退房", None, QtGui.QApplication.UnicodeUTF8))
        self.checkin3.setText(QtGui.QApplication.translate("MainWindow", "入住", None, QtGui.QApplication.UnicodeUTF8))
        self.checkout3.setText(QtGui.QApplication.translate("MainWindow", "退房", None, QtGui.QApplication.UnicodeUTF8))
        self.checkin4.setText(QtGui.QApplication.translate("MainWindow", "入住", None, QtGui.QApplication.UnicodeUTF8))
        self.checkout4.setText(QtGui.QApplication.translate("MainWindow", "退房", None, QtGui.QApplication.UnicodeUTF8))
        self.checkin5.setText(QtGui.QApplication.translate("MainWindow", "入住", None, QtGui.QApplication.UnicodeUTF8))
        self.checkout5.setText(QtGui.QApplication.translate("MainWindow", "退房", None, QtGui.QApplication.UnicodeUTF8))
        self.dayReport.setText(QtGui.QApplication.translate("MainWindow", "日报表", None, QtGui.QApplication.UnicodeUTF8))
        self.weekReport.setText(QtGui.QApplication.translate("MainWindow", "周报表", None, QtGui.QApplication.UnicodeUTF8))
        self.monthReport.setText(QtGui.QApplication.translate("MainWindow", "月报表", None, QtGui.QApplication.UnicodeUTF8))


class ControlMainWindow(QtGui.QMainWindow):
    def __init__(self, parent=None):
        super(ControllerMainWindow, self).__init__(parent)
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

if __name__ == '__main__':
    app = QtGui.QApplication(sys.argv)
    mySW = ControllerMainWindow()
    mySW.show()
    sys.exit(app.exec_())
